function t454_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t454__list_item a[href='"+url+"']").addClass("t-active");$(".t454__list_item a[href='"+url+"/']").addClass("t-active");$(".t454__list_item a[href='"+pathname+"']").addClass("t-active");$(".t454__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t454__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t454__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t454_checkAnchorLinks(recid){if($(window).width()>=960){var t454_navLinks=$("#rec"+recid+" .t454__list_item a:not(.tooltipstered)[href*='#']");if(t454_navLinks.length>0){setTimeout(function(){t454_catchScroll(t454_navLinks)},500)}}}
function t454_catchScroll(t454_navLinks){var t454_clickedSectionId=null,t454_sections=new Array(),t454_sectionIdTonavigationLink=[],t454_interval=100,t454_lastCall,t454_timeoutId;t454_navLinks=$(t454_navLinks.get().reverse());t454_navLinks.each(function(){var t454_cursection=t454_getSectionByHref($(this));if(typeof t454_cursection.attr("id")!="undefined"){t454_sections.push(t454_cursection)}
t454_sectionIdTonavigationLink[t454_cursection.attr("id")]=$(this)});t454_updateSectionsOffsets(t454_sections);$(window).bind('resize',t_throttle(function(){t454_updateSectionsOffsets(t454_sections)},200));$('.t454').bind('displayChanged',function(){t454_updateSectionsOffsets(t454_sections)});setInterval(function(){t454_updateSectionsOffsets(t454_sections)},5000);t454_highlightNavLinks(t454_navLinks,t454_sections,t454_sectionIdTonavigationLink,t454_clickedSectionId);t454_navLinks.click(function(){var clickedSection=t454_getSectionByHref($(this));if(!$(this).hasClass("tooltipstered")&&typeof clickedSection.attr("id")!="undefined"){t454_navLinks.removeClass('t-active');$(this).addClass('t-active');t454_clickedSectionId=t454_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t454_now=new Date().getTime();if(t454_lastCall&&t454_now<(t454_lastCall+t454_interval)){clearTimeout(t454_timeoutId);t454_timeoutId=setTimeout(function(){t454_lastCall=t454_now;t454_clickedSectionId=t454_highlightNavLinks(t454_navLinks,t454_sections,t454_sectionIdTonavigationLink,t454_clickedSectionId)},t454_interval-(t454_now-t454_lastCall))}else{t454_lastCall=t454_now;t454_clickedSectionId=t454_highlightNavLinks(t454_navLinks,t454_sections,t454_sectionIdTonavigationLink,t454_clickedSectionId)}})}
function t454_updateSectionsOffsets(sections){$(sections).each(function(){var t454_curSection=$(this);t454_curSection.attr("data-offset-top",t454_curSection.offset().top)})}
function t454_getSectionByHref(curlink){var curLinkValue=curlink.attr('href').replace(/\s+/g,'').replace(/.*#/,'');if(curlink.is('[href*="#rec"]')){return $(".r[id='"+curLinkValue+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+curLinkValue+"']")}}
function t454_highlightNavLinks(t454_navLinks,t454_sections,t454_sectionIdTonavigationLink,t454_clickedSectionId){var t454_scrollPosition=$(window).scrollTop(),t454_valueToReturn=t454_clickedSectionId;if(t454_sections.length!=0&&t454_clickedSectionId==null&&t454_sections[t454_sections.length-1].attr("data-offset-top")>(t454_scrollPosition+300)){t454_navLinks.removeClass('t-active');return null}
$(t454_sections).each(function(e){var t454_curSection=$(this),t454_sectionTop=t454_curSection.attr("data-offset-top"),t454_id=t454_curSection.attr('id'),t454_navLink=t454_sectionIdTonavigationLink[t454_id];if(((t454_scrollPosition+300)>=t454_sectionTop)||(t454_sections[0].attr("id")==t454_id&&t454_scrollPosition>=$(document).height()-$(window).height())){if(t454_clickedSectionId==null&&!t454_navLink.hasClass('t-active')){t454_navLinks.removeClass('t-active');t454_navLink.addClass('t-active');t454_valueToReturn=null}else{if(t454_clickedSectionId!=null&&t454_id==t454_clickedSectionId){t454_valueToReturn=null}}
return!1}});return t454_valueToReturn}
function t454_setPath(){}
function t454_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t454").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t454").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t454_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t454").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-80px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t454_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t454").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t454_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t454"),burger=el.find(".t454__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t454_opened")})
$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t454_setLogoPadding(recid){if($(window).width()>980){var t454__menu=$('#rec'+recid+' .t454');var t454__logo=t454__menu.find('.t454__logowrapper');var t454__leftpart=t454__menu.find('.t454__leftwrapper');var t454__rightpart=t454__menu.find('.t454__rightwrapper');t454__leftpart.css("padding-right",t454__logo.width()/2+50);t454__rightpart.css("padding-left",t454__logo.width()/2+50)}}
function t670_init(recid){t670_imageHeight(recid);t670_show(recid);t670_hide(recid)}
function t670_show(recid){var el=$('#rec'+recid);var play=el.find('.t670__play');play.click(function(){if($(this).attr('data-slider-video-type')=='youtube'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://www.youtube.com/embed/"+url+"?autoplay=1\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>")}
if($(this).attr('data-slider-video-type')=='vimeo'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://player.vimeo.com/video/"+url+"\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen></iframe>")}
$(this).next().css('z-index','3')})}
function t670_hide(recid){var el=$('#rec'+recid);var body=el.find('.t670__frame');el.on('updateSlider',function(){body.html('').css('z-index','')})}
function t670_imageHeight(recid){var el=$('#rec'+recid);var image=el.find('.t670__separator');image.each(function(){var width=$(this).attr('data-slider-image-width');var height=$(this).attr('data-slider-image-height');var ratio=height/width;var padding=ratio*100;$(this).css('padding-bottom',padding+'%')})}